// Generated by `pnpm rules:bump` (packages/engine/scripts/rules-bump.ts). Don't edit by hand.
import type { CardDef } from './types.ts';

/** Old values of a card's changed fields (null = the field was absent), or null if the card didn't exist yet. */
export type CardPatch = { [K in keyof CardDef]?: CardDef[K] | null } | null;

/** The current rules version: the live card table. */
export const RULES_VERSION = 4;

/** Fingerprint of the live card table's rules (see rulesFingerprint). */
export const RULES_FINGERPRINT = '0xd726527a8290c4cf30884696c284ca2db920a54a0d4b72514d82563fee2c976f';

/**
 * When each version went live (ms; the time it was frozen, or its merge into main). Only used to tell which version
 * a log that doesn't record one was played under.
 */
export const RULES_SINCE: Record<number, number> = {
  1: 0, // 1970-01-01T00:00:00.000Z
  2: 1791195289000, // 2026-10-05T10:14:49.000Z
  3: 1791203805000, // 2026-10-05T12:36:45.000Z
  4: 1791207565697, // 2026-10-05T13:39:25.697Z
};

/** RULES_HISTORY[v]: how version v's cards differ from version v + 1. */
export const RULES_HISTORY: Record<number, Record<number, CardPatch>> = {
  3: {
    34: {"attack":3,"health":3},
    37: {"attack":2,"health":1},
    53: {"targetIfPrediction":null},
    64: {"health":4},
    83: {"attack":5,"health":5},
    134: {"cost":2,"attack":1},
    140: {"attack":2,"health":4},
    165: {"health":6},
  },
  2: {
    5: {"health":3},
    7: {"cost":6},
    10: {"health":3},
    12: {"health":4},
    14: {"health":6},
    17: {"attack":1,"health":1},
    18: {"health":3},
    19: {"health":2},
    20: {"health":4},
    21: {"health":3},
    22: {"text":"Give a friendly unit +2/+2 and Hold.","onPlay":[{"k":"buff","to":"chosen","atk":2,"hp":2,"addKeywords":["hold"]}]},
    23: {"health":6},
    30: {"cost":3},
    45: {"cost":4,"health":5},
    46: {"cost":4,"health":3},
    47: {"health":4},
    48: {"cost":7},
    51: {"cost":2},
    58: {"health":2},
    62: {"health":2},
    63: {"health":3},
    66: {"health":3},
    67: {"health":5},
    68: {"health":4},
    70: {"cost":5,"health":6},
    75: {"cost":3},
    76: {"cost":3,"health":5},
    77: {"health":4},
    82: {"health":6},
    84: {"health":5},
    85: {"cost":7,"health":6},
    98: {"health":4},
    105: {"attack":2},
    111: {"health":3},
    118: {"cost":5},
    121: {"cost":3},
    124: {"health":7},
    128: {"attack":2},
    158: {"cost":7},
    166: {"cost":4},
  },
  1: {
    24: {"cost":8,"attack":7,"health":9},
    32: {"cost":6,"keywords":["rush","ape"],"text":"Rush. Ape. Pump all friendly units."},
    58: {"health":1},
    62: {"health":1},
    63: {"health":2},
    66: {"health":2},
    67: {"health":4},
    68: {"health":3},
    70: {"health":5},
    77: {"health":3},
    78: {"health":4},
    80: {"health":5},
    82: {"health":5},
    84: {"health":4},
    85: {"health":5},
    86: {"health":1},
    88: {"health":3},
    91: {"health":3},
    92: {"health":2},
    93: {"health":5},
    94: {"health":6},
    98: {"health":3},
    100: {"health":6},
    101: {"health":5},
    102: {"health":5},
    104: {"health":8},
    134: {"cost":1},
    135: {"cost":1},
    136: {"cost":1},
    137: {"cost":2,"health":3},
    138: {"cost":2},
    139: {"cost":2},
    140: {"health":5},
    141: {"cost":3},
    142: {"cost":3},
    144: {"cost":4},
    145: {"cost":4},
    147: {"cost":2},
    151: {"cost":3,"health":4},
    152: {"cost":3},
    153: {"cost":4},
    154: {"cost":5,"health":4},
    155: {"cost":6},
    156: {"cost":3},
    158: {"cost":5},
    160: {"cost":7},
    167: {"health":6,"text":"Guard. When this dies, deal 3 damage to the enemy Treasury.","onDeath":[{"k":"damage","to":"enemyTreasury","n":3}]},
  },
};
