/**
 * Embeds the generated Poncho artwork (packages/art/assets/poncho/<cardId>.jpg|png, ideally 512×512) into
 * src/ponchoImages.ts as data URIs, so the art package stays self-contained: the web app, token images,
 * metadata and the player guide all pick the pictures up. Cards without an image keep the vector pal.
 *   pnpm art:poncho-images
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, '../assets/poncho');
const rows = readdirSync(dir)
  .map((f) => /^(\d+)\.(jpe?g|png)$/i.exec(f))
  .filter((m): m is RegExpExecArray => !!m)
  .sort((a, b) => Number(a[1]) - Number(b[1]))
  .map((m) => {
    const mime = m[2].toLowerCase() === 'png' ? 'image/png' : 'image/jpeg';
    return `  ${m[1]}: 'data:${mime};base64,${readFileSync(join(dir, m[0])).toString('base64')}',`;
  });
writeFileSync(resolve(here, '../src/ponchoImages.ts'), `// AUTO-GENERATED by packages/art/scripts/poncho-images.ts from assets/poncho/ — do not edit by hand.
/** Generated Poncho artwork per card id (data URIs). */
export const PONCHO_IMAGES: Record<number, string> = {
${rows.join('\n')}
};
`);
console.log(`embedded ${rows.length} Poncho image(s)`);
