/**
 * Generates contracts/src/generated/Set1Cards.sol from the engine card list,
 * so on-chain card data (race, rarity, chain, starter decks) can never drift from the rules engine.
 *   pnpm gen:cards
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COLLECTIBLE, RACES, starterDeck } from '../src/index.ts';

export const RACE_CODE = { neutral: 0, agents: 1, prophets: 2, brokers: 3, degens: 4 } as const;
export const RARITY_CODE = { common: 0, uncommon: 1, rare: 2, legendary: 3 } as const;
export const CHAIN_CODE = { any: 0, base: 1, robinhood: 2 } as const;

export function renderSolidity(): string {
  const n = COLLECTIBLE.length;
  const rows = COLLECTIBLE.map((c, i) =>
    `        ids[${i}] = ${c.id}; races[${i}] = ${RACE_CODE[c.faction]}; rarities[${i}] = ${RARITY_CODE[c.rarity]}; chains[${i}] = ${CHAIN_CODE[c.chain]}; // ${c.name}`,
  ).join('\n');
  const starters = RACES.map((r) => {
    const d = starterDeck(r);
    return `        if (race == ${RACE_CODE[r]}) return [${d.map((x) => `uint16(${x})`).join(', ')}];`;
  }).join('\n');
  return `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by packages/engine/scripts/gen-solidity.ts — do not edit by hand.
pragma solidity ^0.8.28;

// forgefmt: disable-start
/// @notice Prototype Set 1 card data (${n} collectible cards) mirrored from the rules engine.
library Set1Cards {
    uint256 internal constant COUNT = ${n};

    function all()
        internal
        pure
        returns (uint16[] memory ids, uint8[] memory races, uint8[] memory rarities, uint8[] memory chains)
    {
        ids = new uint16[](${n});
        races = new uint8[](${n});
        rarities = new uint8[](${n});
        chains = new uint8[](${n});
${rows}
    }

    /// @notice Free starter deck (30 cards) for race 1..4.
    function starter(uint8 race) internal pure returns (uint16[30] memory) {
${starters}
        revert("Set1Cards: bad race");
    }
}
// forgefmt: disable-end
`;
}

const here = dirname(fileURLToPath(import.meta.url));
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const out = resolve(here, '../../../contracts/src/generated/Set1Cards.sol');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, renderSolidity());
  console.log(`wrote ${out}`);
}
