/**
 * Freeze the card rules into a new version after a balance change, so matches played before it keep replaying.
 *   pnpm rules:bump [git-ref]
 * Compares the live card table with the one at `git-ref` (default origin/main), stores what changed as the base
 * version's patch in src/rules-history.ts, sets RULES_VERSION to the base's + 1 and pins the new fingerprint.
 * Re-running it on the same branch redoes that version (or drops it if the cards are back to the base's). A base
 * that isn't this branch's own (stale or ahead) is refused: fetch and merge it first. See bumpPlan.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { CARDS } from '../src/cards.ts';
import { bumpPlan, cardPatches, rulesFingerprint } from '../src/rules.ts';
import { RULES_FINGERPRINT, RULES_HISTORY, RULES_VERSION, type CardPatch } from '../src/rules-history.ts';
import type { CardDef } from '../src/types.ts';

const HISTORY_FILE = new URL('../src/rules-history.ts', import.meta.url);

function gitShow(ref: string, path: string): string {
  const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
  return execFileSync('git', ['show', `${ref}:${path}`], { cwd: root, encoding: 'utf8', maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'ignore'] });
}

/** The card table as it was at a git ref. */
export async function cardsAt(ref: string): Promise<CardDef[]> {
  const dir = mkdtempSync(join(tmpdir(), 'forkfall-rules-'));
  for (const f of ['cards.ts', 'types.ts']) {
    const src = gitShow(ref, `packages/engine/src/${f}`);
    writeFileSync(join(dir, f.replace(/\.ts$/, '.mts')), src.replaceAll("from './types.ts'", "from './types.mts'"));
  }
  return (await import(pathToFileURL(join(dir, 'cards.mts')).href)).CARDS as CardDef[];
}

export function writeHistory(version: number, fingerprint: string, history: Record<number, Record<number, CardPatch>>) {
  const block = (patches: Record<number, CardPatch>) => Object.entries(patches)
    .map(([id, p]) => `    ${id}: ${JSON.stringify(p)},`).join('\n');
  const versions = Object.keys(history).map(Number).sort((a, b) => b - a);
  writeFileSync(HISTORY_FILE, `// Generated by \`pnpm rules:bump\` (packages/engine/scripts/rules-bump.ts). Don't edit by hand.
import type { CardDef } from './types.ts';

/** Old values of a card's changed fields (null = the field was absent), or null if the card didn't exist yet. */
export type CardPatch = { [K in keyof CardDef]?: CardDef[K] | null } | null;

/** The current rules version: the live card table. */
export const RULES_VERSION = ${version};

/** Fingerprint of the live card table's rules (see rulesFingerprint). */
export const RULES_FINGERPRINT = '${fingerprint}';

/** RULES_HISTORY[v]: how version v's cards differ from version v + 1. */
export const RULES_HISTORY: Record<number, Record<number, CardPatch>> = {
${versions.map((v) => `  ${v}: {\n${block(history[v])}\n  },`).join('\n')}
};
`);
}

async function main() {
  const ref = process.argv[2] ?? 'origin/main';
  // A stale base would make a version that already shipped look like this branch's own: fetch it first.
  const remote = /^([\w.-]+)\/(.+)$/.exec(ref);
  if (remote) {
    try { execFileSync('git', ['fetch', remote[1], remote[2]], { stdio: 'ignore' }); } catch { console.warn(`could not fetch ${ref}: using the local copy`); }
  }
  const live = rulesFingerprint(CARDS);
  let baseHistory = '';
  try { baseHistory = gitShow(ref, 'packages/engine/src/rules-history.ts'); } catch { /* a base from before rules versions */ }
  const baseVersion = Number(/export const RULES_VERSION = (\d+);/.exec(baseHistory)?.[1]);
  if (!baseVersion) throw new Error(`${ref} has no rules versions: bump against a base that does`);
  const base = await cardsAt(ref);
  const plan = bumpPlan({ version: baseVersion, fingerprint: rulesFingerprint(base) }, { version: RULES_VERSION, fingerprint: RULES_FINGERPRINT }, live);
  switch (plan.action) {
    case 'unchanged': console.log(`card rules unchanged: still v${RULES_VERSION}`); return;
    case 'revert':
      writeFileSync(HISTORY_FILE, baseHistory);
      console.log(`card rules are back to ${ref}'s: v${baseVersion}, this branch's version dropped`);
      return;
    case 'refuse': console.error(plan.reason); process.exitCode = 1; return;
    case 'bump': {
      const history = { ...RULES_HISTORY, [plan.patchOf]: cardPatches(base, CARDS) };
      writeHistory(plan.version, live, history);
      const n = Object.keys(history[plan.patchOf]).length;
      console.log(`card rules v${plan.version}: ${n} card${n === 1 ? '' : 's'} differ${n === 1 ? 's' : ''} from v${plan.patchOf} (${ref})`);
      console.log(`Pin v${plan.version}: ${live} in SHIPPED in packages/engine/test/rules.test.ts.`);
    }
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) await main();
