/**
 * Freeze the card rules into a new version after a balance change, so matches played before it keep replaying.
 *   pnpm rules:bump [git-ref]
 * Compares the live card table with the one at `git-ref` (default origin/main), stores what changed as the
 * previous version's patch in src/rules-history.ts, bumps RULES_VERSION and pins the new fingerprint.
 * Run it once per pull request that changes cards; re-running on the same branch replaces that patch.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { CARDS } from '../src/cards.ts';
import { cardPatches, rulesFingerprint } from '../src/rules.ts';
import { RULES_FINGERPRINT, RULES_HISTORY, RULES_SINCE, RULES_VERSION, type CardPatch } from '../src/rules-history.ts';
import type { CardDef } from '../src/types.ts';

const HISTORY_FILE = new URL('../src/rules-history.ts', import.meta.url);

/** The card table as it was at a git ref. */
export async function cardsAt(ref: string): Promise<CardDef[]> {
  const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
  const dir = mkdtempSync(join(tmpdir(), 'forkfall-rules-'));
  for (const f of ['cards.ts', 'types.ts']) {
    const src = execFileSync('git', ['show', `${ref}:packages/engine/src/${f}`], { cwd: root, encoding: 'utf8', maxBuffer: 1 << 26 });
    writeFileSync(join(dir, f.replace(/\.ts$/, '.mts')), src.replaceAll("from './types.ts'", "from './types.mts'"));
  }
  return (await import(pathToFileURL(join(dir, 'cards.mts')).href)).CARDS as CardDef[];
}

export function writeHistory(
  version: number, fingerprint: string, since: Record<number, number>, history: Record<number, Record<number, CardPatch>>,
) {
  const block = (patches: Record<number, CardPatch>) => Object.entries(patches)
    .map(([id, p]) => `    ${id}: ${JSON.stringify(p)},`).join('\n');
  const versions = Object.keys(history).map(Number).sort((a, b) => b - a);
  writeFileSync(HISTORY_FILE, `// Generated by \`pnpm rules:bump\` (packages/engine/scripts/rules-bump.ts). Don't edit by hand.
import type { CardDef } from './types.ts';

/** Old values of a card's changed fields (null = the field was absent), or null if the card didn't exist yet. */
export type CardPatch = { [K in keyof CardDef]?: CardDef[K] | null } | null;

/** The current rules version: the live card table. */
export const RULES_VERSION = ${version};

/** Fingerprint of the live card table's rules (see rulesFingerprint). */
export const RULES_FINGERPRINT = '${fingerprint}';

/**
 * When each version went live (ms; the time it was frozen, or its merge into main). Only used to tell which version
 * a log that doesn't record one was played under.
 */
export const RULES_SINCE: Record<number, number> = {
${Object.keys(since).map(Number).sort((a, b) => a - b).map((v) => `  ${v}: ${since[v]}, // ${new Date(since[v]).toISOString()}`).join('\n')}
};

/** RULES_HISTORY[v]: how version v's cards differ from version v + 1. */
export const RULES_HISTORY: Record<number, Record<number, CardPatch>> = {
${versions.map((v) => `  ${v}: {\n${block(history[v])}\n  },`).join('\n')}
};
`);
}

async function main() {
  const ref = process.argv[2] ?? 'origin/main';
  const fp = rulesFingerprint(CARDS);
  if (fp === RULES_FINGERPRINT) { console.log(`card rules unchanged: still v${RULES_VERSION}`); return; }
  const base = await cardsAt(ref);
  const baseFp = rulesFingerprint(base);
  // The branch already bumped against this base (the pinned fingerprint isn't the base's): redo that patch.
  const rebump = baseFp !== RULES_FINGERPRINT;
  const prev = rebump ? RULES_VERSION - 1 : RULES_VERSION;
  const history = { ...RULES_HISTORY, [prev]: cardPatches(base, CARDS) };
  writeHistory(prev + 1, fp, { ...RULES_SINCE, [prev + 1]: Date.now() }, history);
  const n = Object.keys(history[prev]).length;
  console.log(`card rules v${prev + 1}: ${n} card${n === 1 ? '' : 's'} differ${n === 1 ? 's' : ''} from v${prev} (${ref})`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) await main();
